import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arsin
 */
public class login extends javax.swing.JFrame {
                public int sr;
                public int status;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 300));
        setPreferredSize(new java.awt.Dimension(350, 300));
        setSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(null);
        getContentPane().add(password);
        password.setBounds(80, 140, 240, 34);
        getContentPane().add(username);
        username.setBounds(80, 90, 240, 31);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 200, 92, 37);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 200, 92, 37);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 63, 30);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 63, 25);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 98, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = username.getText();
        String Pass = new String(password.getPassword());

        try {
            if (user.equals("admin") && Pass.equals("admin")) {
                    main1 m = new main1();
                    m.setVisible(true);
                    this.setVisible(false);
                } else {
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3309/exam",
                        "root", "ARMANS123");
                    Statement stmt = (Statement) con.createStatement();
                    Statement stmt2 = (Statement) con.createStatement();
                      Statement stmt3 = (Statement) con.createStatement();
                    String query = "SELECT * FROM users where username = '"+ user +"'";
                    String query2 = "SELECT * FROM login order by id DESC limit 1";
                    String query3 = "SELECT * FROM login where username =  '"+ user +"'";
                    ResultSet rs2 = stmt2.executeQuery(query2);
                    ResultSet rs3 = stmt3.executeQuery(query3);
                    while (rs3.next())
/* 412:    */       {
                        status =(Integer) rs3.getInt("status"); 
/* 418:    */       }
                    while (rs2.next())
/* 412:    */       {
                        
/* 413:384 */           sr =(Integer) rs2.getInt("id"); 
                        sr++;
/* 418:    */       }
                    ResultSet rs = stmt.executeQuery(query);
                    while (rs.next()) {
                        String user2 = rs.getString("username");
                        String passw = rs.getString("password");
                        String name = rs.getString("name");
                        
                            if (user.equals(user2) && Pass.equals(passw)) {
                               if(status!=2){
                                com.mysql.jdbc.Statement stmt1 = (com.mysql.jdbc.Statement)con.createStatement();
                                String query1 = "INSERT INTO login VALUES(" + sr + ",'" + user2 + "','" + passw + "'," + 1 + ");";
                                stmt1.executeUpdate(query1);

                                instruct z = new instruct(name,user2);
                                z.setVisible(true);

                                this.setVisible(false);
                                break;
                                }else{
                                    JOptionPane.showMessageDialog(null, "You have already taken test!!!!!!");
                                }
                             } else {
                                JOptionPane.showMessageDialog(null, "!!!Invalid username or password.");
                            }
                        
            }}
        } catch (ClassNotFoundException | SQLException n) {
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
