
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arsin
 */
public class score extends javax.swing.JFrame {
        public int score=0;
        public int correct = 0;
        public int yes=0;
    /**
     * Creates new form score
     */
    public score(String abc) {
        initComponents();
        username.setText(abc);
    }

    private score() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 510));
        setPreferredSize(new java.awt.Dimension(500, 510));
        setSize(new java.awt.Dimension(500, 510));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        username.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        username.setText("arsing");
        getContentPane().add(username);
        username.setBounds(270, 100, 170, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Thank You");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 100, 140, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2018-19");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 70, 260, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JAVA EXAM 01");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 30, 260, 50);

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel2.setText("Answered Questions :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 240, 190, 32);

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel3.setText("Correct Answers :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 280, 150, 32);

        l1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(290, 200, 79, 32);

        l2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(290, 240, 79, 32);

        l3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(290, 280, 79, 32);

        jLabel9.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel9.setText("Your Score :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 200, 110, 32);

        filler1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        getContentPane().add(filler1);
        filler1.setBounds(80, 170, 323, 192);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 390, 80, 40);

        jLabel6.setFont(new java.awt.Font("Flipside BRK", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 480, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       String user = username.getText();
        try
             {
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost:3309/exam", "root", "ARMANS123");
                com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement)con.createStatement();
                com.mysql.jdbc.Statement stmt1 = (com.mysql.jdbc.Statement)con.createStatement();
                String query = "select * from test where username = '" + user + "';";
                ResultSet rs = stmt.executeQuery(query);
                    while (rs.next())
/* 412:    */       {
                       int ques_id =(Integer) rs.getInt("ques_id"); 
                       int answer = (Integer)rs.getInt("answer");
                       int answered = (Integer)rs.getInt("answered");
                       if(answered == 1){
                           yes++;
                       }
                       
                       String query1 = "select * from question where id = " + ques_id + ";";
                        ResultSet rs1 = stmt1.executeQuery(query1);
                        while(rs1.next()){
                            int answ = (Integer)rs1.getInt("ans");
                            if(answ == answer){
                                score = score+5;
                                correct++;
                            }else if(answer == 0){
                                score = score+0;
                            }else if(answ != answer){
                                score = score-2;
                            }
                        }
/* 418:    */       }
                l1.setText(""+score);
                l2.setText(""+yes);
                l3.setText(""+correct);
            }
                
            catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException n)
              {
             JOptionPane.showMessageDialog(this, n.getMessage());
              }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
